#! /bin/sh

sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# $HOME/.config/polybar/launch.sh
polybar main -c $HOME/.config/polybar/config &
# feh --no-fehbg --bg-scale /usr/share/backgrounds/glowing_lake.jpg &
feh --no-fehbg --bg-scale /usr/share/backgrounds/future2.jpg &
