#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 45 -xoffset 20 -width 8 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Fantasque Sans Mono 10" <<< " Lock| Logout| Reboot| Shutdown")"
case "$MENU" in
    *Lock) i3lock -t -i "/usr/share/backgrounds/wallpapers-juhraya/Manjaro Juhraya - dark_2.png" ;;
    *Logout) bspc quit;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac
