#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun,window -lines 10 -padding 20 -width 40 -location 1 -yoffset 44 -xoffset 4 -show drun -sidebar-mode -columns 3 -font "Fantasque Sans Mono 10" -theme "centaur" -dpi 192
