#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -yoffset 45 -xoffset 5 -line-padding 4 -columns 1 -width 15 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "Papirus" -font "Fantasque Sans Mono 10" -theme "centaur" -dpi 192
